services:
  bot:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_DSN=${DB_DSN}

  web:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_DSN=${DB_DSN}
    command: uvicorn web.app:app --host 0.0.0.0 --port 8000 --reload
